export const BackgroundWorks = [
  {
    inGameName: "Main Menu Background",
    author: "Andre Moura",
    name: "Abstract colorful background of night star",
    link: "https://www.pexels.com/photo/abstract-colorful-background-of-night-star-4021521/",
  },
  {
    inGameName: "Game Modes Background",
    author: "Maximalfocus",
    name: "Abstract blue Neon Light with Mirrors and cubical spheres in Melbournes CBD",
    link: "https://unsplash.com/photos/VT4rx775FT4",
  },
  {
    inGameName: "Forest Background",
    author: "Francesco Ungaro",
    name: "Trees on a Dark Forest",
    link: "https://www.pexels.com/photo/trees-on-a-dark-forest-1671325/",
  },
  {
    inGameName: "Mountains Background",
    author: "Simon Fitall",
    name: "Hiking to Lac Blanc",
    link: "https://unsplash.com/photos/tvleqH3p1os",
  },
  {
    inGameName: "Snow Background",
    author: "Alession Soggetti",
    name: "Grigone, Italy",
    link: "https://unsplash.com/photos/xTQtznnfgqA",
  },
  {
    inGameName: "Fire Background",
    author: "Maxim Tajer",
    name: "Fire Tornado",
    link: "https://unsplash.com/photos/x3S1aGQNgro",
  },
  {
    inGameName: "Aurora Background",
    author: "Luke Stackpole",
    name: "Westfjords Region, Iceland",
    link: "https://unsplash.com/photos/5Qqkjn4PFPA",
  },
  {
    inGameName: "Space Background",
    author: "Aldebaran S",
    name: "Pelican Nebula",
    link: "https://unsplash.com/photos/zAm8YFpCCsc",
  },
  {
    inGameName: "Neon Future Background",
    author: "Carson Arias",
    name: "Neon Future",
    link: "https://unsplash.com/photos/dygt_Pitso4",
  },
  {
    inGameName: "Goggles Background",
    author: "Roman Raizen",
    name: "N/A",
    link: "https://unsplash.com/photos/gts3hdwWSuo",
  },
  {
    inGameName: "Neon City Background",
    author: "Andrew Haimerl",
    name: "N/A",
    link: "https://unsplash.com/photos/HF3X2TWv1-w",
  },
  {
    inGameName: "Gold Background",
    author: "Jingming Pan",
    name: "N/A",
    link: "https://unsplash.com/photos/Y9U4XZYbSQ4",
  },
  {
    inGameName: "Liquid Background",
    author: "Pawel Czerwinski",
    name: "N/A",
    link: "https://unsplash.com/photos/NTYYL9Eb9y8",
  },
];
