export const Backgrounds = {
  mainMenu: require("../assets/MainMenuBG.jpg"),
  gameModes: require("../assets/GameModesBG.jpg"),
  aurora: require("../assets/AuroraBG.jpg"),
  fire: require("../assets/FireBG.jpg"),
  forest: require("../assets/ForestBG.jpg"),
  mountains: require("../assets/MountainsBG.jpg"),
  snow: require("../assets/SnowBG.jpg"),
  goggles: require("../assets/GogglesBG.jpg"),
  gold: require("../assets/GoldBG.jpg"),
  liquid: require("../assets/LiquidBG.jpg"),
  neonCity: require("../assets/NeonCityBG.jpg"),
  neonFuture: require("../assets/NeonFutureBG.jpg"),
  space: require("../assets/SpaceBG.jpg"),
};
