const Unlockables = {
  1: ["top-red-circle", "right-blue-square", "left-green-triangle"],
  2: ["left-yellow-circle", "right-green-square", "down-orange-shard"],
  3: ["right-purple-circle", "down-green-square", "top-purple-triangle"],
  4: ["down-red-circle", "down-yellow-square", "top-green-shard"],
  5: ["right-green-circle", "top-blue-triangle", "top-yellow-triangle"],
  6: ["right-blue-circle", "right-red-triangle", "outline-red"],
  7: ["down-purple-circle", "top-red-square", "down-red-shard"],
  8: ["right-orange-circle", "down-blue-triangle", "down-blue-square"],
  9: ["left-green-circle", "down-red-square", "left-yellow-triangle"],
  10: ["down-blue-circle", "right-yellow-triangle", "background-aurora"],
  11: ["left-red-circle", "top-red-shard", "top-yellow-circle"],
  12: ["top-purple-circle", "down-red-triangle", "outline-blue"],
  13: ["right-red-circle", "top-red-triangle", "left-blue-shard"],
  14: ["top-silver-circle", "top-green-square", "right-orange-triangle"],
  15: ["down-yellow-circle", "left-red-triangle", "right-blue-shard"],
  16: ["top-green-circle", "down-orange-square", "right-green-triangle"],
  17: ["down-green-circle", "top-blue-shard", "left-red-square"],
  18: ["right-yellow-circle", "left-blue-triangle", "outline-green"],
  19: ["top-blue-circle", "right-red-square", "right-yellow-shard"],
  20: ["left-orange-circle", "right-blue-triangle", "background-fire"],
  21: ["top-orange-circle", "top-green-triangle", "left-blue-square"],
  22: ["left-blue-circle", "down-green-triangle", "right-red-shard"],
  23: ["right-gold-circle", "top-orange-triangle", "left-green-square"],
  24: ["down-orange-circle", "top-blue-square", "outline-yellow"],
  25: ["left-purple-circle", "top-yellow-square", "left-red-shard"],
  26: ["left-silver-circle", "right-purple-triangle", "left-yellow-square"],
  27: ["right-silver-circle", "right-yellow-square", "down-blue-shard"],
  28: ["down-gold-circle", "down-yellow-triangle", "down-green-shard"],
  29: ["down-silver-circle", "left-purple-triangle", "top-purple-square"],
  30: ["top-fluroBlue-circle", "outline-orange", "background-goggles"],
  31: ["left-gold-circle", "down-orange-triangle", "left-purple-square"],
  32: ["top-gold-circle", "down-silver-triangle", "right-green-shard"],
  33: ["down-fluroBlue-circle", "left-orange-triangle", "top-yellow-shard"],
  34: ["right-fluroGreen-circle", "top-silver-triangle", "right-orange-square"],
  35: ["left-fluroBlue-circle", "left-silver-square", "down-yellow-shard"],
  36: ["down-fluroGreen-circle", "down-purple-triangle", "outline-purple"],
  37: ["left-fluroPink-circle", "top-orange-square", "left-green-shard"],
  38: ["right-fluroBlue-circle", "right-silver-triangle", "left-yellow-shard"],
  39: ["top-fluroPink-circle", "left-orange-square", "top-gold-triangle"],
  40: ["left-fluroGreen-circle", "down-gold-triangle", "background-gold"],
  41: ["right-fluroPink-circle", "down-purple-square", "right-orange-shard"],
  42: ["top-fluroGreen-circle", "top-fluroBlue-triangle", "outline-silver"],
  43: ["left-silver-triangle", "right-purple-square", "top-red-pointer"],
  44: ["left-gold-triangle", "right-purple-shard", "top-blue-pointer"],
  45: ["down-fluroBlue-triangle", "top-silver-square", "left-orange-shard"],
  46: ["right-gold-triangle", "down-gold-square", "top-orange-shard"],
  47: ["top-fluroGreen-triangle", "top-gold-square", "top-yellow-pointer"],
  48: ["right-fluroBlue-triangle", "left-purple-shard", "outline-gold"],
  49: ["down-fluroGreen-triangle", "right-silver-square", "top-purple-shard"],
  50: ["left-fluroBlue-triangle", "right-red-pointer", "background-liquid"],
  51: [
    "down-fluroPink-triangle",
    "left-fluroBlue-square",
    "right-silver-shard",
  ],
  52: ["left-fluroGreen-triangle", "left-gold-square", "down-blue-pointer"],
  53: [
    "right-fluroPink-triangle",
    "down-silver-shard",
    "right-fluroBlue-square",
  ],
  54: [
    "right-fluroGreen-triangle",
    "top-fluroGreen-square",
    "outline-fluroBlue",
  ],
  55: ["top-fluroPink-triangle", "right-gold-square", "down-purple-shard"],
  56: ["left-fluroPink-triangle", "down-silver-square", "top-gold-shard"],
  57: ["right-fluroGreen-square", "top-red-letter-a", "left-blue-pointer"],
  58: ["top-fluroBlue-square", "left-silver-shard", "left-red-pointer"],
  59: ["down-fluroGreen-square", "left-gold-shard", "right-blue-pointer"],
  60: ["top-fluroPink-square", "outline-fluroGreen", "background-neoncity"],
  61: ["left-fluroGreen-square", "down-gold-shard", "right-green-pointer"],
  62: ["left-fluroPink-square", "down-red-pointer", "right-blue-letter-a"],
  63: ["down-fluroBlue-square", "right-gold-shard", "left-yellow-pointer"],
  64: ["right-fluroPink-square", "top-silver-shard", "left-red-letter-a"],
  65: ["down-fluroPink-square", "left-green-pointer", "left-fluroBlue-shard"],
  66: ["top-fluroBlue-shard", "top-green-pointer", "outline-fluroPink"],
  67: ["right-fluroGreen-shard", "right-yellow-pointer", "top-green-letter-a"],
  68: ["right-fluroBlue-shard", "down-green-pointer", "top-red-letter-b"],
  69: ["top-fluroPink-shard", "top-orange-pointer", "left-blue-letter-a"],
  70: ["down-fluroGreen-shard", "left-orange-pointer", "background-neonfuture"],
  71: ["right-fluroPink-shard", "top-purple-pointer", "left-blue-letter-b"],
  72: ["down-fluroBlue-shard", "down-yellow-pointer", "left-green-letter-a"],
  73: ["down-fluroPink-shard", "right-orange-pointer", "right-red-letter-b"],
  74: ["left-fluroGreen-shard", "right-purple-pointer", "top-blue-letter-a"],
  75: ["left-fluroPink-shard", "down-purple-pointer", "down-blue-letter-b"],
  76: ["top-fluroGreen-shard", "down-orange-pointer", "right-red-letter-a"],
  77: ["left-purple-pointer", "down-blue-letter-a", "left-red-letter-b"],
  78: ["top-silver-pointer", "down-green-letter-a", "top-blue-letter-b"],
  79: ["left-silver-pointer", "right-yellow-letter-a", "right-blue-letter-b"],
  80: ["right-gold-pointer", "down-red-letter-a", "background-neonfuture"],
  81: ["top-fluroBlue-pointer", "top-yellow-letter-a", "down-red-letter-b"],
  82: ["down-silver-pointer", "right-orange-letter-a", "top-green-letter-b"],
  83: ["top-gold-pointer", "right-green-letter-a", "left-green-letter-b"],
  84: [
    "down-fluroBlue-pointer",
    "down-yellow-letter-a",
    "right-yellow-letter-b",
  ],
  85: ["right-silver-pointer", "left-yellow-letter-a", "down-green-letter-b"],
  86: ["left-gold-pointer", "top-orange-letter-a", "right-green-letter-b"],
  87: [
    "right-fluroGreen-pointer",
    "right-purple-letter-a",
    "down-yellow-letter-b",
  ],
  88: [
    "right-fluroBlue-pointer",
    "down-orange-letter-a",
    "left-yellow-letter-b",
  ],
  89: ["down-gold-pointer", "right-silver-letter-a", "down-orange-letter-b"],
  90: ["top-fluroPink-pointer", "right-gold-letter-a", "background-space"],
  91: [
    "left-fluroBlue-pointer",
    "down-purple-letter-a",
    "right-orange-letter-b",
  ],
  92: ["top-fluroGreen-pointer", "top-silver-letter-a", "top-purple-letter-b"],
  93: ["left-fluroPink-pointer", "top-gold-letter-a", "left-orange-letter-b"],
  94: [
    "down-fluroGreen-pointer",
    "down-silver-letter-a",
    "top-yellow-letter-b",
  ],
  95: [
    "right-fluroPink-pointer",
    "left-orange-letter-a",
    "right-purple-letter-b",
  ],
  96: [
    "left-fluroGreen-pointer",
    "left-purple-letter-a",
    "top-orange-letter-b",
  ],
  97: [
    "down-fluroPink-pointer",
    "top-fluroBlue-letter-a",
    "right-silver-letter-b",
  ],
  98: ["top-purple-letter-a", "top-silver-letter-b", "top-red-letter-x"],
  99: ["left-silver-letter-a", "down-purple-letter-b", "right-blue-letter-y"],
  100: ["right-fluroBlue-letter-a", "top-gold-letter-b", "left-red-letter-x"],
  101: ["down-gold-letter-a", "down-silver-letter-b", "down-blue-letter-y"],
  102: [
    "left-fluroBlue-letter-a",
    "left-purple-letter-b",
    "right-green-letter-x",
  ],
  103: ["top-fluroGreen-letter-a", "left-gold-letter-b", "right-red-letter-y"],
  104: ["left-gold-letter-a", "top-fluroBlue-letter-b", "right-blue-letter-x"],
  105: [
    "left-fluroGreen-letter-a",
    "right-fluroBlue-letter-b",
    "right-red-letter-x",
  ],
  106: [
    "right-fluroGreen-letter-a",
    "left-silver-letter-b",
    "top-red-letter-y",
  ],
  107: ["top-fluroPink-letter-a", "down-gold-letter-b", "left-green-letter-y"],
  108: ["down-fluroBlue-letter-a", "right-gold-letter-b", "down-red-letter-x"],
  109: [
    "left-fluroPink-letter-a",
    "down-fluroBlue-letter-b",
    "left-red-letter-y",
  ],
  110: [
    "down-fluroGreen-letter-a",
    "left-fluroBlue-letter-b",
    "left-blue-letter-x",
  ],
  111: [
    "right-fluroPink-letter-a",
    "top-fluroGreen-letter-b",
    "down-red-letter-y",
  ],
  112: [
    "down-fluroPink-letter-a",
    "left-fluroGreen-letter-b",
    "top-yellow-letter-x",
  ],
  113: [
    "down-fluroGreen-letter-b",
    "top-blue-letter-x",
    "right-yellow-letter-y",
  ],
  114: [
    "left-fluroPink-letter-b",
    "top-orange-letter-x",
    "right-green-letter-y",
  ],
  115: [
    "top-fluroPink-letter-b",
    "left-green-letter-x",
    "down-yellow-letter-y",
  ],
  116: [
    "right-fluroGreen-letter-b",
    "down-blue-letter-x",
    "right-purple-letter-y",
  ],
  117: [
    "right-fluroPink-letter-b",
    "down-fluroPink-letter-x",
    "top-blue-letter-y",
  ],
  118: [
    "down-fluroPink-letter-b",
    "right-yellow-letter-x",
    "right-fluroGreen-letter-y",
  ],
  119: ["top-green-letter-x", "left-yellow-letter-x", "left-blue-letter-y"],
  120: ["down-green-letter-y", "top-orange-letter-y", "down-green-letter-x"],
  121: ["down-yellow-letter-x", "right-orange-letter-x", "top-green-letter-y"],
  122: ["top-yellow-letter-y", "left-orange-letter-y", "top-purple-letter-x"],
  123: [
    "left-orange-letter-x",
    "right-purple-letter-x",
    "left-yellow-letter-y",
  ],
  124: ["right-orange-letter-y", "top-purple-letter-y", "left-silver-letter-x"],
  125: ["down-orange-letter-x", "top-silver-letter-x", "top-gold-letter-y"],
  126: [
    "down-orange-letter-y",
    "left-purple-letter-y",
    "right-silver-letter-x",
  ],
  127: ["left-purple-letter-x", "right-gold-letter-x", "top-silver-letter-y"],
  128: ["down-purple-letter-y", "right-silver-letter-y", "top-gold-letter-x"],
  129: ["down-purple-letter-x", "left-gold-letter-x", "down-silver-letter-y"],
  130: [
    "left-silver-letter-y",
    "right-gold-letter-y",
    "top-fluroBlue-letter-x",
  ],
  131: [
    "down-silver-letter-x",
    "right-fluroBlue-letter-x",
    "left-gold-letter-y",
  ],
  132: ["down-gold-letter-y", "top-fluroBlue-letter-y", "down-gold-letter-x"],
  133: [
    "left-fluroBlue-letter-x",
    "right-fluroGreen-letter-x",
    "top-fluroPink-letter-y",
  ],
  134: [
    "right-fluroBlue-letter-y",
    "left-fluroGreen-letter-y",
    "down-fluroBlue-letter-x",
  ],
  135: [
    "right-fluroPink-letter-x",
    "left-fluroGreen-letter-x",
    "left-fluroBlue-letter-y",
  ],
  136: [
    "down-fluroBlue-letter-y",
    "left-fluroPink-letter-y",
    "top-fluroGreen-letter-x",
  ],
  137: [
    "down-fluroGreen-letter-x",
    "left-fluroPink-letter-x",
    "down-fluroGreen-letter-y",
  ],
  138: [
    "top-fluroGreen-letter-y",
    "right-fluroPink-letter-y",
    "top-fluroPink-letter-x",
  ],
  139: ["down-fluroPink-letter-y"],
};

export default Unlockables;
